name: Build & Post to GitHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: andymeneely/squib
      volumes:
        - my_docker_volume:/usr/src/app
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install fonts
      run: |
        mkdir ~/.fonts
        cp -r fonts/ ~/.fonts
        fc-cache -f -v
    - name: Save git hash to rev.txt
      run: |
        git show -s --pretty="%h %s" > rev.txt
    - name: yarn
      run: yarn install
    - name: rake
      run: |
        bundle exec rake sheets
    - name: Upload built cards
      uses: actions/upload-artifact@v1
      with:
        name: cards
        path: _output
    - name: organize output
      run: |
        rm -rf build/
        mkdir build/
        cp _output/sheet_*.png build/
        cp _output/chit_*.png build/
        cp _output/hex_*.png build/
        cp _output/tracker_*.png build/
        cp _output/help_*_00.png build/
        cp data/crises.json build/
        cp data/events.json build/
        cp rev.txt build/
    - name: Push to ghpages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # Deploy just the build folder
